name: MXCLO SOCIETY
favicon: null
layout_spectrum: 0.2611
typography_spectrum: 0.61282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e7'
    - '#7e7e7e'
    - '#5a5a5a'
    - '#b3b3b3'
    - '#212121'
  brandStrength: 0.25
  lightness: 0.2956215643789619
  saturation: 0.7190057886764407
  rhythmicContrast: 0.2623502458445728
purpose: []
